# Network setup
# Bind to all network interfaces (localhost + network IPs)
server.address=0.0.0.0

# Optional: set/customize port if needed (default 8080)
server.port=8080

# Front-end configuration
spring.application.name=Synergy
app.support.emal=support@synergy.com
app.debug.enable-console=false

# Debug
app.debug=true
app.registration.test-mode=true
spring.output.ansi.enabled=ALWAYS

server.servlet.context-path=

spring.datasource.url=jdbc:postgresql://localhost:5432/medihub
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA/Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Upload Image configurations
# Upload directory (external to app for persistence)
image.upload.dir=${image.upload.dir}

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${spring.mail.username}
spring.mail.password=${spring.mail.password}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=30000
spring.mail.properties.mail.smtp.timeout=30000
spring.mail.properties.mail.smtp.writetimeout=30000

# JWT
jwt.auth.app=${jwt.auth.app}
jwt.auth.secret_key=${jwt.auth.secret_key}
jwt.auth.expires_in=3600

# Security
security.enabled=true

# Google SignIn
spring.security.oauth2.client.registration.google.client-id=${spring.security.oauth2.client.registration.google.client-id}
spring.security.oauth2.client.registration.google.client-secret=${spring.security.oauth2.client.registration.google.client-secret}
spring.security.oauth2.client.registration.google.scope=profile, email
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google
spring.security.oauth2.client.registration.google.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.google.client-name=Google

spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo